# Generated by Django 3.0.9 on 2020-08-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
