# Generated by Django 3.0.9 on 2020-08-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_group',
            field=models.CharField(default='blank', editable=False, max_length=400),
            preserve_default=False,
        ),
    ]
