# Generated by Django 3.0.9 on 2020-08-05 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_product_inventory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(default='blank', editable=False, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(default='blank', editable=False, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pcs_Per_Unit',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='blank', editable=False, max_length=400),
            preserve_default=False,
        ),
    ]
